### ISSUE TITLE
Make Git LFS optional in examples

### ISSUE THREAD

**Issue by lucamlouzada** [gentzkow/GentzkowLabTemplate#22]
This issue is part of an effort to implement substantive improvements to the lab template, as discussed in https://github.com/gentzkow/GentzkowLabTemplate/issues/16.

In this issue, the goal is to work on how to robustly require Git LFS and also create an easy option for people who want to use the repo without Git LFS. The main points to be addressed per the decision in [plans for next steps](https://github.com/gentzkow/GentzkowLabTemplate/blob/4ee0b9edb56e7b243786f0f57cde299ccca12cc1/issue/nextstep.lyx) are:

1. The template can run out of the box without Git LFS installed and it functions correctly as a template on Github. This means we need to revise the way we currently commit data and figure files into non Git LFS. 
2. The template is preconfigured so that someone who *does* want to use LFS can do so easily.
3. We have good ways of enforcing that all of our lab projects *must* be using LFS.

I am assigning myself to work on this. I will start by revising the commits of large files in the template examples, and changing the `gitattributes` file as well as the `check_setup.sh` file to allow users to use the template without Git LFS. I will then create an additional folder in `examples` with the default settings for using Git LFS, which will be standard in the lab projects. I will run tests to ensure both points (2) and (3) above are enforced.

**Comment by lucamlouzada** [comment]
I have pushed several changes to this branch.

- In eaf16eb, I re-added all the large files to the remote repository without LFS tracking. This should allow users who do not have LFS installed to properly use the repository as a template, fixing the issues discussed in [#15 (comment)](https://github.com/gentzkow/GentzkowLabTemplate/issues/15#issuecomment-2347119360) 
- In 1889f1e, I removed file tracking from the template `.gitattributes`, so that the default setting does not use LFS
- In 6b999df, I commented out the lines in `check_setup.sh` that checked for LFS to be installed, so that users can activate this check if they opt to use LFS
- In 63f0d45 I introduced the LFS extension, which will allow users to activate it for their projects as an optional setting (and will be standard in all lab projects). I included a `README.md` file with instructions and a `.sh` script that users should run to initialize LFS. I made this script more complex than the previous version in [template_archive/setup/lfs_setup](https://github.com/gentzkow/template_archive/blob/d76fd2d1f18076edccc59646a4fb6850039b9489/setup/lfs_setup.sh) to handle the case in which users have already been using the repository without LFS and then want to activate it. The script will then re-upload files with LFS tracking.

**Comment by gentzkow** [comment]
Looking good!

Small suggestion: When I ran `add_lfs.sh` from inside the `/examples/git_lfs/` directory it didn't find any of the tracked files outside that directory. When I ran it from the repo root it worked fine. Maybe add a `REPO_ROOT` variable at the top of `add_lfs.sh` similar to what we have in `make.sh` so `add_lfs.sh` runs correctly no matter what the `cwd`?

**Comment by lucamlouzada** [comment]
Thanks @gentzkow , this sounds good. Will implement this in this branch.

**Comment by lucamlouzada** [comment]
**Summary:**
In this issue we implemented the Git LFS framework for the new template, by making it an optional feature in `/examples`. The PR #25 was merged to main in [083638a](https://github.com/gentzkow/GentzkowLabTemplate/commit/083638a306c7941761ffbd7e40a7bc35b0c81199). The stable branch with these changes is [here](https://github.com/gentzkow/GentzkowLabTemplate/tree/6b999df266962bffa58e4de9741d91f2beae4d6f).
