### ISSUE TITLE
Add matlab and lyx run scripts and examples

### ISSUE THREAD

**Issue by lucamlouzada** [gentzkow/GentzkowLabTemplate#23]
This issue is part of an effort to implement substantive improvements to the lab template, as discussed in https://github.com/gentzkow/GentzkowLabTemplate/issues/16.

In this issue, the goal is to add examples, `run_xx` scripts and instructions for MATLAB and Lyx. 

I am assigning myself to work on this. Because the `make.sh` and `run_xx` scripts were changed in #18 to improve error handling, this issue should only be closed after #18 and the associated PR #19 are closed, so that the new run_xx scripts are standardized with the other versions. I will start by creating the scripts following the initial commit in #19, and it will be necessary to update them afterwards in case there are any changes during the review.

**Comment by lucamlouzada** [comment]
I have pushed several changes to this branch.

- In fbc1bb6, I introduced the `run_matlab.sh` command, which follows the structure in the other `run_xx` scripts pushed in [#19](https://github.com/gentzkow/GentzkowLabTemplate/pull/19). Running it requires that `MATLAB` is properly installed and added to path for command line usage. 
- In e594e5a, I added two example scripts for data wrangling and analysis with `MATLAB`, following the exact same pattern as the scripts in R, Python and Stata
- In 7c96bca, I introduced the `run_lyx.sh` command, which follows a similar structure to the `run_latex` version pushed in [#19](https://github.com/gentzkow/GentzkowLabTemplate/pull/19). One important difference is that `Lyx` is called with the [full path](https://github.com/gentzkow/GentzkowLabTemplate/commit/7c96bca547d1994379c6bab37d08e86d5f95bc11#diff-ff060015f5dcfa63c514f726b4ac5961fd91d028eda9306f0e3e5c155f149c5fR50) to prevent issues that happen due to the way `Lyx` handles environments in the command line when converting .jpg objects to pdf. A minor fix to comments in this script was added in a881c10.
- In 5d1fdd2 and 5c2603b, I pushed example `Lyx` scripts for compiling an example paper and slide deck, closely following the Latex examples.
- In 063fe83, I copied the `.bib` file from the `examples/latex` folder to the `examples/lyx` folder, so that users know that they should copy that file to `4_paper/source` if they want to compile a paper using `Lyx`

 I have not added instructions yet because I believe they should be standardized with the instructions for R, Python and Stata which depend on the current approach for error handling being approved in #19. Therefore, README files will be updated in a future step.

**Comment by gentzkow** [comment]
Looks great so far @lucamlouzada. Thanks!

**Comment by lucamlouzada** [comment]
Update: in 01b81a9 I merged recent changes to the main branch following the conclusion of #28 , #27 , #19, #25. Then, in 
58819f8 I updated `run_matlab.sh` and `run_lyx.sh` to reflect the final logic of the other `run_xxx` scripts per #19.

**Comment by lucamlouzada** [comment]
**Summary:**

In this issue we created new [`run_matlab.sh` ](https://github.com/gentzkow/GentzkowLabTemplate/blob/f12d1fb9e76e8cd6881025db5c19edd0e352c18c/lib/shell/run_matlab.sh)and [`run_lyx.sh`](https://github.com/gentzkow/GentzkowLabTemplate/blob/f12d1fb9e76e8cd6881025db5c19edd0e352c18c/lib/shell/run_lyx.sh) scripts, along with example files following the structure in the examples for other languages. Details of these changes can be found in the issue thread as well as in the associated PR #29. We also pushed a minor update to the other `run_xxx` scripts and updated `local_env_template.sh` to reflect the default commands for matlab and lyx. 

Changes were merged to main in f12d1fb. Final state of the issue branch is [here](https://github.com/gentzkow/GentzkowLabTemplate/tree/f12d1fb9e76e8cd6881025db5c19edd0e352c18c) and of the test branch is [here](https://github.com/gentzkow/GentzkowLabTemplate/tree/b1af3b041022ea216db0a1b914e4ba9e1910158a).
